import org.apache.dubbo.config.spring.beans.factory.annotation.CompatibleReferenceAnnotationBeanPostProcessor;
public class FunctionUse8370 {
public void funcUse() {
CompatibleReferenceAnnotationBeanPostProcessor compatiblereferenceannotationbeanpostprocessor = new CompatibleReferenceAnnotationBeanPostProcessor();
compatiblereferenceannotationbeanpostprocessor.getInjectedFieldReferenceBeanMap();
}
}