import org.apache.dubbo.config.spring.beans.factory.annotation.CompatibleReferenceAnnotationBeanPostProcessor;
public class FunctionUse8374 {
public void funcUse() {
CompatibleReferenceAnnotationBeanPostProcessor compatiblereferenceannotationbeanpostprocessor = new CompatibleReferenceAnnotationBeanPostProcessor();
compatiblereferenceannotationbeanpostprocessor.findMethodReferenceMetadata(null);
}
}